param(
    [string]$SourcePath = (Join-Path $PSScriptRoot '..\OptiScaler\upscalers\dlssnr\DLSSNRBoundary.hlsl'),
    [Parameter(Mandatory = $true)][string]$OutputPath,
    [string]$FxcPath = ''
)

$ErrorActionPreference = 'Stop'
function Get-ShaderFileHash([string]$Path) {
    # Use the framework API as well in Windows PowerShell build environments
    # whose inherited PSModulePath does not expose Get-FileHash.
    $sha = [Security.Cryptography.SHA256]::Create()
    $stream = [IO.File]::OpenRead([IO.Path]::GetFullPath($Path))
    try { [BitConverter]::ToString($sha.ComputeHash($stream)).Replace('-', '') }
    finally { $stream.Dispose(); $sha.Dispose() }
}
if (-not $FxcPath) {
    $sdk = Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\10\bin'
    $FxcPath = Get-ChildItem -LiteralPath $sdk -Filter fxc.exe -Recurse -File |
        Where-Object { $_.FullName -match '\\x64\\fxc\.exe$' } |
        Sort-Object FullName -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $FxcPath -or -not (Test-Path -LiteralPath $FxcPath)) {
    throw 'DLSSNR exterior shaders require the Windows SDK x64 fxc.exe at build time.'
}
$source = Get-Content -LiteralPath $SourcePath -Raw -Encoding UTF8
$OutputPath = [IO.Path]::GetFullPath($OutputPath)
$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
$encoding = [Text.UTF8Encoding]::new($false)
$compilerHash = Get-ShaderFileHash $FxcPath
$shaderNames = [ordered]@{
    BoundarySeed = 0
    BoundaryDiffuse = 1
    BoundaryFit = 2
    BoundaryApply = 3
    BoundaryApplyInPlace = 3
}
$header = [Text.StringBuilder]::new()
[void]$header.AppendLine('// Generated by tools/compile_dlssnr_extrapolation.ps1. Do not edit.')
[void]$header.AppendLine('#pragma once')
[void]$header.AppendLine('namespace DlssNrExtrapolation::Shaders {')
$manifest = @()
foreach ($entry in $shaderNames.GetEnumerator()) {
    # Normalize checkout line endings, then hash the exact input compiled below.
    $inPlace = if ($entry.Key -eq 'BoundaryApplyInPlace') { 1 } else { 0 }
    $shader = "#define DLSSNR_BOUNDARY_STAGE $($entry.Value)`n#define DLSSNR_BOUNDARY_INPLACE $inPlace`n" + $source.Replace("`r`n", "`n")
    $sha = [Security.Cryptography.SHA256]::Create()
    try { $sourceHash = [BitConverter]::ToString($sha.ComputeHash($encoding.GetBytes($shader))).Replace('-', '') }
    finally { $sha.Dispose() }
    $shaderPath = Join-Path $outputDirectory ($entry.Key + '.hlsl')
    $objectPath = Join-Path $outputDirectory ($entry.Key + '.cso')
    $stampPath = Join-Path $outputDirectory ($entry.Key + '.json')
    $cached = $false
    if ((Test-Path -LiteralPath $stampPath) -and (Test-Path -LiteralPath $objectPath)) {
        try {
            $stamp = Get-Content -LiteralPath $stampPath -Raw | ConvertFrom-Json
            $cached = $stamp.sourceSha256 -eq $sourceHash -and $stamp.compilerSha256 -eq $compilerHash -and
                $stamp.options -eq '/O3 /T cs_5_0 /E CSMain' -and
                $stamp.bytecodeSha256 -eq (Get-ShaderFileHash $objectPath)
        } catch { $cached = $false }
    }
    if (-not $cached) {
        [IO.File]::WriteAllText($shaderPath, $shader, $encoding)
        $timer = [Diagnostics.Stopwatch]::StartNew()
        $compilerOutput = & $FxcPath /nologo /O3 /T cs_5_0 /E CSMain /Fo $objectPath $shaderPath 2>&1
        if ($LASTEXITCODE -ne 0) { throw "DLSSNR $($entry.Key) compilation failed:`n$($compilerOutput -join "`n")" }
        Write-Host ('DLSSNR {0}: compiled in {1:F1} ms' -f $entry.Key, $timer.Elapsed.TotalMilliseconds)
    } else {
        Write-Host "DLSSNR $($entry.Key): verified cached bytecode"
    }
    $bytes = [IO.File]::ReadAllBytes($objectPath)
    if ($bytes.Length -lt 32 -or [Text.Encoding]::ASCII.GetString($bytes, 0, 4) -ne 'DXBC') {
        throw "Invalid bytecode for $($entry.Value)"
    }
    $stamp = [ordered]@{
        name = $entry.Key
        sourceSha256 = $sourceHash
        compilerSha256 = $compilerHash
        options = '/O3 /T cs_5_0 /E CSMain'
        bytecodeSha256 = Get-ShaderFileHash $objectPath
        bytecodeBytes = $bytes.Length
    }
    [IO.File]::WriteAllText($stampPath, ($stamp | ConvertTo-Json), $encoding)
    $manifest += $stamp
    [void]$header.AppendLine("// $($entry.Value) source SHA256: $sourceHash")
    [void]$header.AppendLine("inline constexpr unsigned char $($entry.Key)[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        [void]$header.Append('    ')
        for ($j = $i; $j -lt [Math]::Min($i + 16, $bytes.Length); ++$j) {
            [void]$header.AppendFormat('0x{0:X2},', $bytes[$j])
        }
        [void]$header.AppendLine()
    }
    [void]$header.AppendLine('};')
}
[void]$header.AppendLine('}')
$headerText = $header.ToString()
if (-not (Test-Path -LiteralPath $OutputPath) -or
    [IO.File]::ReadAllText($OutputPath) -cne $headerText) {
    $temporary = $OutputPath + '.' + [guid]::NewGuid().ToString('N') + '.tmp'
    [IO.File]::WriteAllText($temporary, $headerText, $encoding)
    Move-Item -LiteralPath $temporary -Destination $OutputPath -Force
}
[IO.File]::WriteAllText(($OutputPath + '.json'), ($manifest | ConvertTo-Json), $encoding)
